// priority: 0

// Adjust Biome Restrictions to your Liking, sadly atm can only have 1 biome per recipe, so copy paste and change the name if you want/need more

ServerEvents.recipes(event => {

    // Controller Craft

    event.recipes.gtceu.assembly_line('deep_vein_mining_drill_rig')
        .itemInputs('gtceu:iv_large_miner', '4x #gtceu:circuits/luv', '6x gtceu:tungstensteel_gearbox', '6x gtceu:tungsten_carbide_plate', '4x gtceu:platinum_single_cable')
        .itemOutputs('gtceu:deep_vein_mining_drill_rig')
        .inputFluids(
            Fluid.of('gtceu:titanium', 4608),
            Fluid.of('gtceu:iridium', 4608),
            Fluid.of('gtceu:soldering_alloy', 2304),
            Fluid.of('gtceu:lubricant', 8000)
        )
        .duration(500)
        .EUt(8000)


    // Group 1 - Mountains and Old Mountains Ores

        // IV Recipes
    event.recipes.gtceu.deep_vein_mining('tfc_mountains_iv')
        .chancedInput('gtceu:tungsten_grinding_head', 250, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 20000))
        .chancedOutput('4x gtceu:raw_magnetite', 6900, 0)
        .chancedOutput('4x gtceu:raw_vanadium_magnetite', 4000, 0)
        .chancedOutput('4x gtceu:raw_chromite', 5000, 0)
        .chancedOutput('4x minecraft:raw_gold', 6000, 0)
        .chancedOutput('4x gtceu:raw_yellow_limonite', 4000, 0)
        .chancedOutput('4x gtceu:raw_malachite', 4000, 0)
        .chancedOutput('4x gtceu:raw_beryllium', 3000, 0)
        .chancedOutput('4x gtceu:raw_emerald', 3000, 0)
        .chancedOutput('4x gtceu:raw_redstone', 4000, 0)
        .chancedOutput('4x gtceu:raw_cinnabar', 3000, 0)
        .chancedOutput('4x gtceu:raw_ruby', 3000, 0)
        .chancedOutput('4x gtceu:raw_goethite', 4000, 0)
        .chancedOutput('4x gtceu:raw_pentlandite', 4000, 0)
        .chancedOutput('4x gtceu:raw_rock_salt', 2000, 0)
        .chancedOutput('4x gtceu:raw_lapis', 2000, 0)
        .chancedOutput('4x gtceu:raw_lazurite', 2000, 0)
        .chancedOutput('4x gtceu:raw_sodalite', 2000, 0)
        .chancedOutput('4x gtceu:raw_calcite', 3000, 0)
        .chancedOutput('4x gtceu:raw_graphite', 4000, 0)
        .chancedOutput('4x gtceu:raw_diamond', 3000, 0)
        .chancedOutput('4x gtceu:raw_coal', 5000, 0)
        .circuit(1)
        .biome('tfc:mountains')
        .duration(1200)
        .EUt(8000)

    event.recipes.gtceu.deep_vein_mining('tfc_old_mountains_iv')
        .chancedInput('gtceu:tungsten_grinding_head', 250, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 20000))
        .chancedOutput('4x gtceu:raw_magnetite', 6900, 0)
        .chancedOutput('4x gtceu:raw_vanadium_magnetite', 4000, 0)
        .chancedOutput('4x gtceu:raw_chromite', 5000, 0)
        .chancedOutput('4x minecraft:raw_gold', 6000, 0)
        .chancedOutput('4x gtceu:raw_yellow_limonite', 4000, 0)
        .chancedOutput('4x gtceu:raw_malachite', 4000, 0)
        .chancedOutput('4x gtceu:raw_beryllium', 3000, 0)
        .chancedOutput('4x gtceu:raw_emerald', 3000, 0)
        .chancedOutput('4x gtceu:raw_redstone', 4000, 0)
        .chancedOutput('4x gtceu:raw_cinnabar', 3000, 0)
        .chancedOutput('4x gtceu:raw_ruby', 3000, 0)
        .chancedOutput('4x gtceu:raw_goethite', 4000, 0)
        .chancedOutput('4x gtceu:raw_pentlandite', 4000, 0)
        .chancedOutput('4x gtceu:raw_rock_salt', 2000, 0)
        .chancedOutput('4x gtceu:raw_lapis', 2000, 0)
        .chancedOutput('4x gtceu:raw_lazurite', 2000, 0)
        .chancedOutput('4x gtceu:raw_sodalite', 2000, 0)
        .chancedOutput('4x gtceu:raw_calcite', 3000, 0)
        .chancedOutput('4x gtceu:raw_graphite', 4000, 0)
        .chancedOutput('4x gtceu:raw_diamond', 3000, 0)
        .chancedOutput('4x gtceu:raw_coal', 5000, 0)
        .circuit(1)
        .biome('tfc:old_mountains')
        .duration(1200)
        .EUt(8000)

        // LuV Recipes
    event.recipes.gtceu.deep_vein_mining('tfc_mountains_luv')
        .chancedInput('gtceu:tungsten_grinding_head', 400, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 30000))
        .chancedOutput('4x gtceu:raw_opal', 3000, 0)
        .chancedOutput('4x gtceu:raw_neodymium', 4000, 0)
        .chancedOutput('4x gtceu:raw_monazite', 6900, 0)
        .chancedOutput('4x gtceu:raw_bastnasite', 4000, 0)
        .chancedOutput('4x gtceu:raw_grossular', 3000, 0)
        .chancedOutput('4x gtceu:raw_spessartine', 3000, 0)
        .chancedOutput('4x gtceu:raw_pyrolusite', 4000, 0)
        .chancedOutput('4x gtceu:raw_tantalite', 4000, 0)
        .chancedOutput('4x gtceu:raw_plutonium', 1000, 0)
        .chancedOutput('4x gtceu:raw_platinum', 2000, 0)
        .chancedOutput('4x gtceu:raw_palladium', 2000, 0)
        .chancedOutput('4x gtceu:raw_thorium', 2000, 0)
        .chancedOutput('4x gtceu:raw_pitchblende', 2000, 0)
        .chancedOutput('4x gtceu:raw_uraninite', 2000, 0)
        .chancedOutput('4x gtceu:raw_cooperite', 5000, 0)
        .circuit(2)
        .biome('tfc:mountains')
        .duration(1200)
        .EUt(32000)

    event.recipes.gtceu.deep_vein_mining('tfc_old_mountains_luv')
        .chancedInput('gtceu:tungsten_grinding_head', 400, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 30000))
        .chancedOutput('4x gtceu:raw_opal', 3000, 0)
        .chancedOutput('4x gtceu:raw_neodymium', 4000, 0)
        .chancedOutput('4x gtceu:raw_monazite', 6900, 0)
        .chancedOutput('4x gtceu:raw_bastnasite', 4000, 0)
        .chancedOutput('4x gtceu:raw_grossular', 3000, 0)
        .chancedOutput('4x gtceu:raw_spessartine', 3000, 0)
        .chancedOutput('4x gtceu:raw_pyrolusite', 4000, 0)
        .chancedOutput('4x gtceu:raw_tantalite', 4000, 0)
        .chancedOutput('4x gtceu:raw_plutonium', 1000, 0)
        .chancedOutput('4x gtceu:raw_platinum', 2000, 0)
        .chancedOutput('4x gtceu:raw_palladium', 2000, 0)
        .chancedOutput('4x gtceu:raw_thorium', 2000, 0)
        .chancedOutput('4x gtceu:raw_pitchblende', 2000, 0)
        .chancedOutput('4x gtceu:raw_uraninite', 2000, 0)
        .chancedOutput('4x gtceu:raw_cooperite', 5000, 0)
        .circuit(2)
        .biome('tfc:old_mountains')
        .duration(1200)
        .EUt(32000)



    // Group 2 - Canyons, Low Canyons, Badlands and Inverted Badlands

        // IV Recipes
    event.recipes.gtceu.deep_vein_mining('tfc_canyons_iv')
        .chancedInput('gtceu:tungsten_grinding_head', 250, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 20000))
        .chancedOutput('4x gtceu:raw_chalcopyrite', 6900, 0)
        .chancedOutput('4x gtceu:raw_pyrite', 3000, 0)
        .chancedOutput('4x gtceu:raw_sulfur', 4000, 0)
        .chancedOutput('4x gtceu:raw_sphalerite', 4000, 0)
        .chancedOutput('4x gtceu:raw_galena', 4000, 0)
        .chancedOutput('4x gtceu:raw_silver', 6000, 0)
        .chancedOutput('4x gtceu:raw_lead', 3000, 0)
        .chancedOutput('4x gtceu:raw_bauxite', 6000, 0)
        .chancedOutput('4x gtceu:raw_aluminium', 3000, 0)
        .chancedOutput('4x gtceu:raw_stibnite', 3000, 0)
        .chancedOutput('4x gtceu:raw_asbestos', 3000, 0)
        .chancedOutput('4x gtceu:raw_chalcocite', 3000, 0)
        .chancedOutput('4x gtceu:raw_bornite', 3000, 0)
        .chancedOutput('4x gtceu:raw_quartzite', 2000, 0)
        .chancedOutput('4x gtceu:raw_certus_quartz', 3000, 0)
        .chancedOutput('4x gtceu:raw_saltpeter', 2000, 0)
        .chancedOutput('4x gtceu:raw_electrotine', 2000, 0)
        .chancedOutput('4x gtceu:raw_alunite', 2000, 0)
        .chancedOutput('4x gtceu:raw_magnesite', 4000, 0)
        .chancedOutput('4x gtceu:raw_glauconite_sand', 2000, 0)
        .chancedOutput('4x gtceu:raw_realgar', 4000, 0)
        .circuit(1)
        .biome('tfc:canyons')
        .duration(1200)
        .EUt(8000)

    event.recipes.gtceu.deep_vein_mining('tfc_low_canyons_iv')
        .chancedInput('gtceu:tungsten_grinding_head', 250, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 20000))
        .chancedOutput('4x gtceu:raw_chalcopyrite', 6900, 0)
        .chancedOutput('4x gtceu:raw_pyrite', 3000, 0)
        .chancedOutput('4x gtceu:raw_sulfur', 4000, 0)
        .chancedOutput('4x gtceu:raw_sphalerite', 4000, 0)
        .chancedOutput('4x gtceu:raw_galena', 4000, 0)
        .chancedOutput('4x gtceu:raw_silver', 6000, 0)
        .chancedOutput('4x gtceu:raw_lead', 3000, 0)
        .chancedOutput('4x gtceu:raw_bauxite', 6000, 0)
        .chancedOutput('4x gtceu:raw_aluminium', 3000, 0)
        .chancedOutput('4x gtceu:raw_stibnite', 3000, 0)
        .chancedOutput('4x gtceu:raw_asbestos', 3000, 0)
        .chancedOutput('4x gtceu:raw_chalcocite', 3000, 0)
        .chancedOutput('4x gtceu:raw_bornite', 3000, 0)
        .chancedOutput('4x gtceu:raw_quartzite', 2000, 0)
        .chancedOutput('4x gtceu:raw_certus_quartz', 3000, 0)
        .chancedOutput('4x gtceu:raw_saltpeter', 2000, 0)
        .chancedOutput('4x gtceu:raw_electrotine', 2000, 0)
        .chancedOutput('4x gtceu:raw_alunite', 2000, 0)
        .chancedOutput('4x gtceu:raw_magnesite', 4000, 0)
        .chancedOutput('4x gtceu:raw_glauconite_sand', 2000, 0)
        .chancedOutput('4x gtceu:raw_realgar', 4000, 0)
        .circuit(1)
        .biome('tfc:low_canyons')
        .duration(1200)
        .EUt(8000)        

    event.recipes.gtceu.deep_vein_mining('tfc_badlands_iv')
        .chancedInput('gtceu:tungsten_grinding_head', 250, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 20000))
        .chancedOutput('4x gtceu:raw_chalcopyrite', 6900, 0)
        .chancedOutput('4x gtceu:raw_pyrite', 3000, 0)
        .chancedOutput('4x gtceu:raw_sulfur', 4000, 0)
        .chancedOutput('4x gtceu:raw_sphalerite', 4000, 0)
        .chancedOutput('4x gtceu:raw_galena', 4000, 0)
        .chancedOutput('4x gtceu:raw_silver', 6000, 0)
        .chancedOutput('4x gtceu:raw_lead', 3000, 0)
        .chancedOutput('4x gtceu:raw_bauxite', 6000, 0)
        .chancedOutput('4x gtceu:raw_aluminium', 3000, 0)
        .chancedOutput('4x gtceu:raw_stibnite', 3000, 0)
        .chancedOutput('4x gtceu:raw_asbestos', 3000, 0)
        .chancedOutput('4x gtceu:raw_chalcocite', 3000, 0)
        .chancedOutput('4x gtceu:raw_bornite', 3000, 0)
        .chancedOutput('4x gtceu:raw_quartzite', 2000, 0)
        .chancedOutput('4x gtceu:raw_certus_quartz', 3000, 0)
        .chancedOutput('4x gtceu:raw_saltpeter', 2000, 0)
        .chancedOutput('4x gtceu:raw_electrotine', 2000, 0)
        .chancedOutput('4x gtceu:raw_alunite', 2000, 0)
        .chancedOutput('4x gtceu:raw_magnesite', 4000, 0)
        .chancedOutput('4x gtceu:raw_glauconite_sand', 2000, 0)
        .chancedOutput('4x gtceu:raw_realgar', 4000, 0)
        .circuit(1)
        .biome('tfc:badlands')
        .duration(1200)
        .EUt(8000)    

    event.recipes.gtceu.deep_vein_mining('tfc_inverted_badlands_iv')
        .chancedInput('gtceu:tungsten_grinding_head', 250, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 20000))
        .chancedOutput('4x gtceu:raw_chalcopyrite', 6900, 0)
        .chancedOutput('4x gtceu:raw_pyrite', 3000, 0)
        .chancedOutput('4x gtceu:raw_sulfur', 4000, 0)
        .chancedOutput('4x gtceu:raw_sphalerite', 4000, 0)
        .chancedOutput('4x gtceu:raw_galena', 4000, 0)
        .chancedOutput('4x gtceu:raw_silver', 6000, 0)
        .chancedOutput('4x gtceu:raw_lead', 3000, 0)
        .chancedOutput('4x gtceu:raw_bauxite', 6000, 0)
        .chancedOutput('4x gtceu:raw_aluminium', 3000, 0)
        .chancedOutput('4x gtceu:raw_stibnite', 3000, 0)
        .chancedOutput('4x gtceu:raw_asbestos', 3000, 0)
        .chancedOutput('4x gtceu:raw_chalcocite', 3000, 0)
        .chancedOutput('4x gtceu:raw_bornite', 3000, 0)
        .chancedOutput('4x gtceu:raw_quartzite', 2000, 0)
        .chancedOutput('4x gtceu:raw_certus_quartz', 3000, 0)
        .chancedOutput('4x gtceu:raw_saltpeter', 2000, 0)
        .chancedOutput('4x gtceu:raw_electrotine', 2000, 0)
        .chancedOutput('4x gtceu:raw_alunite', 2000, 0)
        .chancedOutput('4x gtceu:raw_magnesite', 4000, 0)
        .chancedOutput('4x gtceu:raw_glauconite_sand', 2000, 0)
        .chancedOutput('4x gtceu:raw_realgar', 4000, 0)
        .circuit(1)
        .biome('tfc:inverted_badlands')
        .duration(1200)
        .EUt(8000)    

        // LuV Recipes
    event.recipes.gtceu.deep_vein_mining('tfc_canyons_luv')
        .chancedInput('gtceu:tungsten_grinding_head', 400, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 30000))
        .chancedOutput('4x gtceu:raw_wulfenite', 3000, 0)
        .chancedOutput('4x gtceu:raw_molybdenite', 3000, 0)
        .chancedOutput('4x gtceu:raw_molybdenum', 3000, 0)
        .chancedOutput('4x gtceu:raw_powellite', 3000, 0)
        .chancedOutput('4x gtceu:raw_ilmenite', 6900, 0)
        .chancedOutput('4x gtceu:raw_topaz', 3000, 0)
        .chancedOutput('4x gtceu:raw_blue_topaz', 3000, 0)
        .chancedOutput('4x gtceu:raw_red_garnet', 2000, 0)
        .chancedOutput('4x gtceu:raw_yellow_garnet', 2000, 0)
        .chancedOutput('4x gtceu:raw_zeolite', 2000, 0)
        .chancedOutput('4x gtceu:raw_bentonite', 3000, 0)
        .chancedOutput('4x gtceu:raw_olivine', 3000, 0)
        .chancedOutput('4x gtceu:raw_barite', 4000, 0)
        .chancedOutput('4x gtceu:raw_nether_quartz', 4000, 0)
        .chancedOutput('4x gtceu:raw_diatomite', 2000, 0)
        .circuit(2)
        .biome('tfc:canyons')
        .duration(1200)
        .EUt(32000)

    event.recipes.gtceu.deep_vein_mining('tfc_low_canyons_luv')
        .chancedInput('gtceu:tungsten_grinding_head', 400, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 30000))
        .chancedOutput('4x gtceu:raw_wulfenite', 3000, 0)
        .chancedOutput('4x gtceu:raw_molybdenite', 3000, 0)
        .chancedOutput('4x gtceu:raw_molybdenum', 3000, 0)
        .chancedOutput('4x gtceu:raw_powellite', 3000, 0)
        .chancedOutput('4x gtceu:raw_ilmenite', 6900, 0)
        .chancedOutput('4x gtceu:raw_topaz', 3000, 0)
        .chancedOutput('4x gtceu:raw_blue_topaz', 3000, 0)
        .chancedOutput('4x gtceu:raw_red_garnet', 2000, 0)
        .chancedOutput('4x gtceu:raw_yellow_garnet', 2000, 0)
        .chancedOutput('4x gtceu:raw_zeolite', 2000, 0)
        .chancedOutput('4x gtceu:raw_bentonite', 3000, 0)
        .chancedOutput('4x gtceu:raw_olivine', 3000, 0)
        .chancedOutput('4x gtceu:raw_barite', 4000, 0)
        .chancedOutput('4x gtceu:raw_nether_quartz', 4000, 0)
        .chancedOutput('4x gtceu:raw_diatomite', 2000, 0)
        .circuit(2)
        .biome('tfc:low_canyons')
        .duration(1200)
        .EUt(32000)

    event.recipes.gtceu.deep_vein_mining('tfc_badlands_luv')
        .chancedInput('gtceu:tungsten_grinding_head', 400, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 30000))
        .chancedOutput('4x gtceu:raw_wulfenite', 3000, 0)
        .chancedOutput('4x gtceu:raw_molybdenite', 3000, 0)
        .chancedOutput('4x gtceu:raw_molybdenum', 3000, 0)
        .chancedOutput('4x gtceu:raw_powellite', 3000, 0)
        .chancedOutput('4x gtceu:raw_ilmenite', 6900, 0)
        .chancedOutput('4x gtceu:raw_topaz', 3000, 0)
        .chancedOutput('4x gtceu:raw_blue_topaz', 3000, 0)
        .chancedOutput('4x gtceu:raw_red_garnet', 2000, 0)
        .chancedOutput('4x gtceu:raw_yellow_garnet', 2000, 0)
        .chancedOutput('4x gtceu:raw_zeolite', 2000, 0)
        .chancedOutput('4x gtceu:raw_bentonite', 3000, 0)
        .chancedOutput('4x gtceu:raw_olivine', 3000, 0)
        .chancedOutput('4x gtceu:raw_barite', 4000, 0)
        .chancedOutput('4x gtceu:raw_nether_quartz', 4000, 0)
        .chancedOutput('4x gtceu:raw_diatomite', 2000, 0)
        .circuit(2)
        .biome('tfc:badlands')
        .duration(1200)
        .EUt(32000)

    event.recipes.gtceu.deep_vein_mining('tfc_inverted_badlands_luv')
        .chancedInput('gtceu:tungsten_grinding_head', 400, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 30000))
        .chancedOutput('4x gtceu:raw_wulfenite', 3000, 0)
        .chancedOutput('4x gtceu:raw_molybdenite', 3000, 0)
        .chancedOutput('4x gtceu:raw_molybdenum', 3000, 0)
        .chancedOutput('4x gtceu:raw_powellite', 3000, 0)
        .chancedOutput('4x gtceu:raw_ilmenite', 6900, 0)
        .chancedOutput('4x gtceu:raw_topaz', 3000, 0)
        .chancedOutput('4x gtceu:raw_blue_topaz', 3000, 0)
        .chancedOutput('4x gtceu:raw_red_garnet', 2000, 0)
        .chancedOutput('4x gtceu:raw_yellow_garnet', 2000, 0)
        .chancedOutput('4x gtceu:raw_zeolite', 2000, 0)
        .chancedOutput('4x gtceu:raw_bentonite', 3000, 0)
        .chancedOutput('4x gtceu:raw_olivine', 3000, 0)
        .chancedOutput('4x gtceu:raw_barite', 4000, 0)
        .chancedOutput('4x gtceu:raw_nether_quartz', 4000, 0)
        .chancedOutput('4x gtceu:raw_diatomite', 2000, 0)
        .circuit(2)
        .biome('tfc:inverted_badlands')
        .duration(1200)
        .EUt(32000)

    // Group 3 - Plains and Plateau

        // IV Recipes
    event.recipes.gtceu.deep_vein_mining('tfc_plains_iv')
        .chancedInput('gtceu:tungsten_grinding_head', 250, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 20000))
        .chancedOutput('4x gtceu:raw_hematite', 6900, 0)
        .chancedOutput('4x minecraft:raw_iron', 3000, 0)
        .chancedOutput('4x minecraft:raw_copper', 3000, 0)
        .chancedOutput('4x gtceu:raw_tin', 3000, 0)
        .chancedOutput('4x gtceu:raw_tetrahedrite', 4000, 0)
        .chancedOutput('4x gtceu:raw_cassiterite', 6000, 0)
        .chancedOutput('4x gtceu:raw_bismuth', 3000, 0)
        .chancedOutput('4x gtceu:raw_cobalt', 3000, 0)
        .chancedOutput('4x gtceu:raw_cobaltite', 4000, 0)
        .chancedOutput('4x gtceu:raw_nickel', 4000, 0)
        .chancedOutput('4x gtceu:raw_garnierite', 5000, 0)
        .chancedOutput('4x gtceu:raw_salt', 4000, 0)
        .chancedOutput('4x gtceu:raw_lepidolite', 3000, 0)
        .chancedOutput('4x gtceu:raw_spodumene', 3000, 0)
        .chancedOutput('4x gtceu:raw_cassiterite_sand', 3000, 0)
        .chancedOutput('4x gtceu:raw_apatite', 2000, 0)
        .chancedOutput('4x gtceu:raw_tricalcium_phosphate', 2000, 0)
        .chancedOutput('4x gtceu:raw_pyrochlore', 5000, 0)
        .chancedOutput('4x gtceu:raw_talc', 2000, 0)
        .chancedOutput('4x gtceu:raw_trona', 2000, 0)
        .chancedOutput('4x gtceu:raw_soapstone', 2000, 0)
        .circuit(1)
        .biome('tfc:plains')
        .duration(1200)
        .EUt(8000)

    event.recipes.gtceu.deep_vein_mining('tfc_plateau_iv')
        .chancedInput('gtceu:tungsten_grinding_head', 250, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 20000))
        .chancedOutput('4x gtceu:raw_hematite', 6900, 0)
        .chancedOutput('4x minecraft:raw_iron', 3000, 0)
        .chancedOutput('4x minecraft:raw_copper', 3000, 0)
        .chancedOutput('4x gtceu:raw_tin', 3000, 0)
        .chancedOutput('4x gtceu:raw_tetrahedrite', 4000, 0)
        .chancedOutput('4x gtceu:raw_cassiterite', 6000, 0)
        .chancedOutput('4x gtceu:raw_bismuth', 3000, 0)
        .chancedOutput('4x gtceu:raw_cobalt', 3000, 0)
        .chancedOutput('4x gtceu:raw_cobaltite', 4000, 0)
        .chancedOutput('4x gtceu:raw_nickel', 4000, 0)
        .chancedOutput('4x gtceu:raw_garnierite', 5000, 0)
        .chancedOutput('4x gtceu:raw_salt', 4000, 0)
        .chancedOutput('4x gtceu:raw_lepidolite', 3000, 0)
        .chancedOutput('4x gtceu:raw_spodumene', 3000, 0)
        .chancedOutput('4x gtceu:raw_cassiterite_sand', 3000, 0)
        .chancedOutput('4x gtceu:raw_apatite', 2000, 0)
        .chancedOutput('4x gtceu:raw_tricalcium_phosphate', 2000, 0)
        .chancedOutput('4x gtceu:raw_pyrochlore', 5000, 0)
        .chancedOutput('4x gtceu:raw_talc', 2000, 0)
        .chancedOutput('4x gtceu:raw_trona', 2000, 0)
        .chancedOutput('4x gtceu:raw_soapstone', 2000, 0)
        .circuit(1)
        .biome('tfc:plateau')
        .duration(1200)
        .EUt(8000)

        // LuV Recipes
    event.recipes.gtceu.deep_vein_mining('tfc_plains_luv')
        .chancedInput('gtceu:tungsten_grinding_head', 400, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 30000))
        .chancedOutput('4x gtceu:raw_borax', 3000, 0)
        .chancedOutput('4x gtceu:raw_fullers_earth', 2000, 0)
        .chancedOutput('4x gtceu:raw_gypsum', 2000, 0)
        .chancedOutput('4x gtceu:raw_sapphire', 3000, 0)
        .chancedOutput('4x gtceu:raw_green_sapphire', 2000, 0)
        .chancedOutput('4x gtceu:raw_almandine', 2000, 0)
        .chancedOutput('4x gtceu:raw_pyrope', 2000, 0)
        .chancedOutput('4x gtceu:raw_lithium', 3000, 0)
        .chancedOutput('4x gtceu:raw_amethyst', 3000, 0)
        .chancedOutput('4x gtceu:raw_kyanite', 3000, 0)
        .chancedOutput('4x gtceu:raw_mica', 2000, 0)
        .chancedOutput('4x gtceu:raw_pollucite', 4000, 0)
        .chancedOutput('4x gtceu:raw_scheelite', 6900, 0)
        .chancedOutput('4x gtceu:raw_tungstate', 6900, 0)
        .chancedOutput('4x gtceu:raw_naquadah', 3000, 0)
        .circuit(2)
        .biome('tfc:plains')
        .duration(1200)
        .EUt(32000)

    event.recipes.gtceu.deep_vein_mining('tfc_plateau_luv')
        .chancedInput('gtceu:tungsten_grinding_head', 400, 0)
        .inputFluids(Fluid.of('gtceu:drilling_fluid', 30000))
        .chancedOutput('4x gtceu:raw_borax', 3000, 0)
        .chancedOutput('4x gtceu:raw_fullers_earth', 2000, 0)
        .chancedOutput('4x gtceu:raw_gypsum', 2000, 0)
        .chancedOutput('4x gtceu:raw_sapphire', 3000, 0)
        .chancedOutput('4x gtceu:raw_green_sapphire', 2000, 0)
        .chancedOutput('4x gtceu:raw_almandine', 2000, 0)
        .chancedOutput('4x gtceu:raw_pyrope', 2000, 0)
        .chancedOutput('4x gtceu:raw_lithium', 3000, 0)
        .chancedOutput('4x gtceu:raw_amethyst', 3000, 0)
        .chancedOutput('4x gtceu:raw_kyanite', 3000, 0)
        .chancedOutput('4x gtceu:raw_mica', 2000, 0)
        .chancedOutput('4x gtceu:raw_pollucite', 4000, 0)
        .chancedOutput('4x gtceu:raw_scheelite', 6900, 0)
        .chancedOutput('4x gtceu:raw_tungstate', 6900, 0)
        .chancedOutput('4x gtceu:raw_naquadah', 3000, 0)
        .circuit(2)
        .biome('tfc:plateau')
        .duration(1200)
        .EUt(32000)


})